### PR TITLE
Added input validation to OpenFile and CreateFile methods #322

### PR DESCRIPTION
**Pull request by TheBaronOfDubstep**
Recreated the pull request to ensure I have only verified commits and all code style checks will succeed

### CODE REVIEW

**Comment by TheBaronOfDubstep** [comment]
@LiorBanai hold off on this pull request. I am adding a workaround that will handle this for you regardless

**Comment by TheBaronOfDubstep** [comment]
@LiorBanai As I do not know whether or not this nuget is cross platform, I will not introduce a binding to kernel32.dll. This code is ready for merge

**Comment by LiorBanai** [comment]
Thanks! .  I'll review it. And yes it is cross platform but we can check the running platform and bind only on windows.

**Comment by TheBaronOfDubstep** [comment]
> Thanks! . I'll review it. And yes it is cross platform but we can check the running platform and bind only on windows.

Sounds great. I'll just read up on the compiler macros for that, and I'll send you another that will compile. I have no idea why this one won't.

**Comment by TheBaronOfDubstep** [comment]
@LiorBanai new version is up and should compile better :)

**Comment by TheBaronOfDubstep** [comment]
@LiorBanai Again, sorry for the commit spam. Tried to stay within guidelines of the static code analysis, but it promotes outdated code standards (for c# 4) and advocates against current best practices (for c# 7)

**Comment by LiorBanai** [comment]
@TheBaronOfDubstep Don't worry about the static code analysis.. it is indeed  need revising...
I plan to add editorconfig not far away.

**Comment by LiorBanai** [comment]
AS long ad the code compiled and unit tests passes that is  what important.
any chance you can add some specific tests?

**Comment by TheBaronOfDubstep** [comment]
I can add tests for the input sanitation, but I am not sure if the tests will run if I include the kernel32.dll call in them

**Comment by TheBaronOfDubstep** [comment]
@LiorBanai Tests are added for the added functionality of this PR.

**Comment by LiorBanai** [comment]
@TheBaronOfDubstep I'll review it this weekend.
Thanks! :)

**Comment by LiorBanai** [comment]
@TheBaronOfDubstep Thanks

**Pull request merged**
